import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/menu";
import Sidebar from "@/components/sidebar";
import {
  LayoutPanelTop,
  Video,
  LucideIcon,
  UserRound,
  ClipboardPlus,
} from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems: Array<{
  name: string;
  icon: React.ReactElement<LucideIcon>;
  active: boolean;
}> = [
  { name: "Overview", icon: <LayoutPanelTop size={24} />, active: true },
  { name: "Meeting List", icon: <Video size={24} />, active: false },
  { name: "Member List", icon: <UserRound size={24} />, active: false },
  { name: "Reports", icon: <ClipboardPlus size={24} />, active: false },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row min-h-screen">
          <aside className="w-80 flex-shrink-0">
            <Sidebar companyName="Jarad Co." menuItems={menuItems} />
          </aside>
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
